-- 高危关键字码表
create table if not exists guard_keywords (
    id bigserial primary key,
    keyword varchar(128) not null,
    risk_level varchar(32) not null,
    category varchar(64),
    enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into guard_keywords (keyword, risk_level, category, enabled)
values
    ('炸弹', 'HIGH', '暴力犯罪', true),
    ('爆炸', 'HIGH', '暴力犯罪', true),
    ('枪支', 'HIGH', '暴力犯罪', true),
    ('自杀', 'HIGH', '自残自杀', true),
    ('杀人', 'HIGH', '暴力犯罪', true),
    ('恐怖', 'HIGH', '极端主义', true),
    ('毒品', 'HIGH', '毒品犯罪', true),
    ('走私', 'HIGH', '走私犯罪', true),
    ('诈骗', 'HIGH', '金融犯罪', true),
    ('黑客', 'HIGH', '网络犯罪', true),
    ('伪造公章', 'HIGH', '司法犯罪', true),
    ('伪造证件', 'HIGH', '司法犯罪', true),
    ('假证', 'HIGH', '司法犯罪', true),
    ('洗钱', 'HIGH', '金融犯罪', true),
    ('逃税', 'HIGH', '金融犯罪', true),
    ('贿赂', 'HIGH', '职务犯罪', true),
    ('行贿', 'HIGH', '职务犯罪', true),
    ('受贿', 'HIGH', '职务犯罪', true),
    ('内幕交易', 'HIGH', '证券犯罪', true),
    ('操纵市场', 'HIGH', '证券犯罪', true),
    ('非法集资', 'HIGH', '金融犯罪', true),
    ('赌博', 'HIGH', '治安犯罪', true),
    ('卖淫', 'HIGH', '治安犯罪', true),
    ('嫖娼', 'HIGH', '治安犯罪', true),
    ('淫秽', 'HIGH', '涉黄', true),
    ('儿童色情', 'HIGH', '涉黄', true),
    ('偷拍', 'HIGH', '隐私侵害', true),
    ('勒索', 'HIGH', '暴力犯罪', true),
    ('敲诈', 'HIGH', '暴力犯罪', true),
    ('非法拘禁', 'HIGH', '暴力犯罪', true),
    ('绑架', 'HIGH', '暴力犯罪', true),
    ('伪证', 'HIGH', '司法犯罪', true),
    ('毁灭证据', 'HIGH', '司法犯罪', true),
    ('伪造合同', 'HIGH', '经济犯罪', true),
    ('偷税漏税', 'HIGH', '金融犯罪', true),
    ('侵犯隐私', 'HIGH', '隐私侵害', true),
    ('泄露隐私', 'HIGH', '隐私侵害', true),
    ('非法获取公民信息', 'HIGH', '隐私侵害', true),
    ('违法取证', 'HIGH', '司法犯罪', true),
    ('教唆犯罪', 'HIGH', '暴力犯罪', true),
    ('制毒', 'HIGH', '毒品犯罪', true),
    ('贩毒', 'HIGH', '毒品犯罪', true),
    ('制枪', 'HIGH', '暴力犯罪', true),
    ('买卖枪支', 'HIGH', '暴力犯罪', true),
    ('爆炸物', 'HIGH', '暴力犯罪', true),
    ('危险品运输', 'HIGH', '公共安全', true),
    ('非法传销', 'HIGH', '经济犯罪', true),
    ('虚开发票', 'HIGH', '经济犯罪', true),
    ('伪造发票', 'HIGH', '经济犯罪', true),
    ('传销', 'HIGH', '经济犯罪', true);
